// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgnUlp5JEaazfHahyP-Sgxr1gNP5rD7NU',
    appId: '1:242221448895:web:2d54cb2de1ec7fcb17d00a',
    messagingSenderId: '242221448895',
    projectId: 'spendsense-23an',
    databaseURL:
        'https://spendsense-23an-default-rtdb.asia-southeast1.firebasedatabase.app',
    authDomain: 'spendsense-23an.firebaseapp.com',
    storageBucket: 'spendsense-23an.firebasestorage.app',
    measurementId: 'G-0K47TNVMQK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkLObSr6Ta1uAP_giW541MUrQgrbIoC-E',
    appId: '1:242221448895:android:52016db3df7acf2f17d00a',
    messagingSenderId: '242221448895',
    projectId: 'spendsense-23an',
    databaseURL:
        'https://spendsense-23an-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spendsense-23an.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdzs5faNlysI4ErlZS4ClZ8j4OkluLS34',
    appId: '1:242221448895:ios:9abad4dd5bff655817d00a',
    messagingSenderId: '242221448895',
    projectId: 'spendsense-23an',
    databaseURL:
        'https://spendsense-23an-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spendsense-23an.firebasestorage.app',
    iosBundleId: 'com.example.spendSense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdzs5faNlysI4ErlZS4ClZ8j4OkluLS34',
    appId: '1:242221448895:ios:9abad4dd5bff655817d00a',
    messagingSenderId: '242221448895',
    projectId: 'spendsense-23an',
    databaseURL:
        'https://spendsense-23an-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spendsense-23an.firebasestorage.app',
    iosBundleId: 'com.example.spendSense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgnUlp5JEaazfHahyP-Sgxr1gNP5rD7NU',
    appId: '1:242221448895:web:f83717026279685f17d00a',
    messagingSenderId: '242221448895',
    projectId: 'spendsense-23an',
    databaseURL:
        'https://spendsense-23an-default-rtdb.asia-southeast1.firebasedatabase.app',
    authDomain: 'spendsense-23an.firebaseapp.com',
    storageBucket: 'spendsense-23an.firebasestorage.app',
    measurementId: 'G-2TRD6XMGV1',
  );
}
